// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjmlqzlfxzjcfyhamkyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbWxxemxmeHpqY2Z5aGFta3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODMzMjMsImV4cCI6MjA2NTg1OTMyM30.hkfCOL0pWdiN4IzTeMWM1dARpR9IeX4BK3FQbK9RUps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);